### ISSUE TITLE
Creation de base données

### ISSUE THREAD

**Issue by Laraje** [hillal98/gpiprojet#1]
il faut mettre ajour la base de donnée en créant des Access au administrateur.
on a deux type d administrateurs : directeur de la stratégie (il valide les cibles de routage : c'est a dire les informations de la publicité) y a le responsable du routage (il valide la publicité)

un login pour utilisateurs et admin
Inscription pour utilisateurs

**Comment by hillal98** [comment]
ouiii tout a fait dcr 
de tout façon y a belkacem qui est dessus 
le plus important maintenant c est de revoir l interface et de la finir et bien sur mettre en relation les pub avec l applications
